### ISSUE TITLE
Unknown / Ambiguous License information

### ISSUE THREAD

**Issue by warthog9** [solo-io/solo-kit#200]
The project, currently, doesn't seem to have any known license information pertaining to it.  There's no /LICENSE file, and none of the core files have any header indications on what copyright / license the files are actually under.  There's pieces that do indicate license information for the piece, https://github.com/solo-io/solo-kit/blame/master/test/mocks/api/doc/google/rpc/status.proto.sk.md#L13, for example but overall I'm not seeing anything or solo-kit itself.

Can some clarification be made as to the actual license of the code?

**Comment by yuval-k** [comment]
like everything we do in the open source, this will be apache. we'll fix this shortly
