### ISSUE TITLE
I got an error using go mod

### ISSUE THREAD

**Issue by lou-lan** [solo-io/solo-kit#349]
the filepath "/var/folders/9v/0_n3fj_x5yq7dvyzl3ps61kw0000gn/T/788663949/github.com/xxxxx" does not exist. this means that solo-kit did not compile any proto files.this is not technically an error, but could be indicative of an incorrect setup.

**Comment by ilackarms** [comment]
@lou-lan can you share the command / code you executed which produced this error? some background on what you are trying to do with solo kit?
