### ISSUE TITLE
Will the control-plane implementation cause traffic drop?

### ISSUE THREAD

**Issue by wZH-CN** [solo-io/solo-kit#368]
In the [`process`](https://github.com/solo-io/solo-kit/blob/master/pkg/api/v1/control-plane/server/generic_server.go#L188) method of server.server, the sequence of responses to send doesn't seem to be ordered.
According to the xds protocol documentations, however, the responses should be sent in cds->eds->lds->rds order, otherwise traffic drop might happen.

If I use solo-kit control-plane as my ads server, will traffic drop happen?

**Comment by yuval-k** [comment]
envoy's configuration model is eventually consistent, so this shouldn't be a problem in real world workloads, and infact we have not noticed this being an issue.

**Comment by wZH-CN** [comment]
Thanks for the clarification.
