### ISSUE TITLE
Clean up `UnmarshalJSON` methods and `UnmarshalResource` function

### ISSUE THREAD

**Issue by jackstine** [solo-io/solo-kit#528]
The function `UnmarshalResource()` is used in Gloo in multiple places, particularly with the types. But the method `UnmarshalJSON()` does not appear to be used at all and does not seem to be called in both Gloo and in solo-kit.
[Gloo Resources](https://github.com/solo-io/gloo/blob/validate-rate-limit-config/projects/gloo/pkg/api/v1/kube/apis/gloo.solo.io/v1/types.go#L171)
[Gateway Resources](https://github.com/solo-io/gloo/blob/validate-rate-limit-config/projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/types.go#L372)

**Comment by nfuden** [comment]
UnmarshalJSON is used to support https://cs.opensource.google/go/go/+/go1.19.4:src/encoding/json/decode.go;l=97
namely it implements the interface. This means that any unmarshal call will find this and work off of it.
