### ISSUE TITLE
Canary Status Reporting

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/solo-kit#529]
# Description
We do not support multiple namespaces on a resource as would exist in a canary upgrade

# Context
https://github.com/solo-io/solo-kit/blob/master/pkg/api/shared/status.go#L70

We need to remove this check. It's intended to ensure that there is only 1 status on the resource ,but in reality we may have multiple, when multiple controllers are reading the same resources.

Slack context: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1670354796059129

We should use https://github.com/solo-io/solo-kit/blob/master/pkg/utils/statusutils/env.go#L11 to determine which status entry in the map to modify.

# Definition of Done
- Merged/released changes in solo-kit with tests
- Merged/released in gloo enterprise, with basic smoke tests to write multiple statuses
- Backport fix to Gloo LTS branches

**Comment by jenshu** [comment]
possibly related https://github.com/solo-io/gloo/issues/7731
